const fs = require('fs');
const qr = fs.readFileSync('qr-hbj-app.png');
const base64 = qr.toString('base64');
const partes = [];
partes.push('<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>HBJ App</title><style>');
partes.push('*{margin:0;padding:0;box-sizing:border-box}');
partes.push('body{background:#f0f0f0;display:flex;justify-content:center;align-items:center;min-height:100vh;font-family:Arial,sans-serif}');
partes.push('.cartel{background:#0B1F3A;width:600px;padding:40px;border-radius:20px;color:white;text-align:center}');
partes.push('.cruz{background:#1A8FE3;width:72px;height:72px;border-radius:14px;margin:0 auto 16px;font-size:32px;display:flex;align-items:center;justify-content:center}');
partes.push('h1{font-size:22px;font-weight:700;margin-bottom:6px}');
partes.push('.sub{color:#7BB8E8;font-size:13px;margin-bottom:20px}');
partes.push('.divider{background:#1A8FE3;height:1px;opacity:.4;margin-bottom:20px}');
partes.push('.desc{font-size:15px;font-weight:600;margin-bottom:6px}');
partes.push('.desc2{color:#7BB8E8;font-size:12px;margin-bottom:20px}');
partes.push('.qr-box{background:white;border-radius:16px;padding:16px;display:inline-block;margin-bottom:20px}');
partes.push('.qr-box img{width:260px;height:260px;display:block}');
partes.push('.instrucciones{background:#112540;border-radius:12px;padding:16px 20px;margin-bottom:20px;text-align:left}');
partes.push('.instrucciones p{font-size:13px;color:#7BB8E8;font-weight:600;margin-bottom:8px}');
partes.push('.instrucciones li{font-size:12px;color:white;margin-bottom:5px;list-style:none}');
partes.push('.features{display:flex;gap:12px;margin-bottom:20px}');
partes.push('.feature{background:#112540;border-radius:10px;padding:14px 10px;flex:1}');
partes.push('.feature .icon{font-size:22px;margin-bottom:6px}');
partes.push('.feature .name{font-size:11px;font-weight:600;color:white;margin-bottom:3px}');
partes.push('.feature .detail{font-size:10px;color:#7BB8E8}');
partes.push('.divider2{background:#1A8FE3;height:1px;opacity:.3;margin-bottom:14px}');
partes.push('.creds{font-size:11px;color:#7BB8E8;line-height:1.8;margin-bottom:10px}');
partes.push('.footer{font-size:10px;color:#3A5A7A}');
partes.push('@media print{body{background:white}}');
partes.push('</style></head><body><div class="cartel">');
partes.push('<div class="cruz">+</div>');
partes.push('<h1>Hospital Boliviano Japones</h1>');
partes.push('<p class="sub">Control de Atencion Medica</p>');
partes.push('<div class="divider"></div>');
partes.push('<p class="desc">Descarga nuestra app</p>');
partes.push('<p class="desc2">Consulta tus citas y historial medico desde tu celular</p>');
partes.push('<div class="qr-box"><img src="data:image/png;base64,' + base64 + '" alt="QR"/></div>');
partes.push('<div class="instrucciones"><p>Como descargar</p>');
partes.push('<li>1. Escanea el QR con la camara de tu celular</li>');
partes.push('<li>2. Acepta instalar desde fuentes desconocidas</li>');
partes.push('<li>3. Ingresa con tu N de historial y CI</li></div>');
partes.push('<div class="features">');
partes.push('<div class="feature"><div class="icon">Citas</div><div class="name">Ver citas</div><div class="detail">Agenda medica</div></div>');
partes.push('<div class="feature"><div class="icon">Historial</div><div class="name">Historial</div><div class="detail">Registros</div></div>');
partes.push('<div class="feature"><div class="icon">Docs</div><div class="name">Documentos</div><div class="detail">Resultados</div></div>');
partes.push('</div><div class="divider2"></div>');
partes.push('<p class="creds">Usuario: N de historial | Contrasena: CI</p>');
partes.push('<p class="footer">HBJ Sistema v1.0 - Solo Android</p>');
partes.push('</div></body></html>');
fs.writeFileSync('cartel-hbj-app.html', partes.join(''), 'utf8');
console.log('Cartel generado correctamente');
